# Generated by Django 5.0.9 on 2024-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_medicine_description_alter_medicine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
